const disposableDomains = new Set([
  // Common disposable services
  'mailinator.com', 'guerrillamail.com', 'tempmail.com', 'throwaway.email',
  'yopmail.com', 'sharklasers.com', 'guerrillamailblock.com', 'grr.la',
  'guerrillamail.info', 'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.net',
  'guerrillamail.org', 'spam4.me', 'trashmail.com', 'trashmail.me', 'trashmail.net',
  'trashmail.at', 'trashmail.io', 'trashmail.xyz', 'dispostable.com',
  'maildrop.cc', 'mailnull.com', 'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'spamgourmet.me', 'mailnesia.com', 'mailforspam.com',
  'spamfree24.org', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info',
  'spamfree24.net', 'spam.la', 'spamgob.com', 'spamhole.com', 'spamify.com',
  'spamthisplease.com', 'fakemail.net', 'fakeinbox.com', 'tempinbox.com',
  'temp-mail.org', 'temp-mail.ru', 'tempmail.net', 'tempmail.de', 'tempmail.eu',
  'tempr.email', 'discard.email', 'discardmail.com', 'discardmail.de',
  'spamwc.de', 'spamwc.net', 'spamwc.org', 'spamwc.cf', 'spamwc.ga',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'nospam.ze.tc', 'nospamfor.us', 'nospamthanks.info',
  'mailexpire.com', 'mailfreeonline.com', 'mailguard.me',
  'throwam.com', 'throwam.net', 'throwam.org',
  'mohmal.com', 'spamgap.com', 'getairmail.com', 'filzmail.com',
  'zzrgg.com', 'binkmail.com', 'bobmail.info', 'dayrep.com',
  'dingbone.com', 'dump-email.info', 'dumpandfuck.com', 'dumpmail.de',
  'dumpyemail.com', 'emailias.com', 'emailinfive.com', 'emailsensei.com',
  'emailtemporario.com.br', 'emailthe.net', 'emailtmp.com', 'emailwarden.com',
  'emailx.at.hm', 'emailxfer.com', 'emz.net', 'fakemail.fr', 'fastacura.com',
  'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com', 'fastmazda.com',
  'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
  'fasttoyota.com', 'fastyamaha.com', 'fizmail.com', 'frapmail.com',
  'garliclife.com', 'get1mail.com', 'get2mail.fr', 'getonemail.com',
  'getonemail.net', 'ghosttexter.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'gowikibooks.com', 'gowikicampus.com', 'gowikicars.com',
  'gowikifilms.com', 'gowikigames.com', 'gowikimusic.com', 'gowikinetwork.com',
  'gowikitravel.com', 'gowikitv.com', 'grandmamail.com', 'grandmasmail.com',
  'h8s.org', 'haltospam.com', 'herp.in', 'hidemail.de', 'hidzz.com',
  'hmamail.com', 'hopemail.biz', 'hurrycane.com', 'ieatspam.eu',
  'ieatspam.info', 'ihateyoualot.info', 'iheartspam.org', 'imails.info',
  'inbax.tk', 'inbox.si', 'inboxalias.com', 'inboxclean.com', 'inboxclean.org',
  'infocom.zp.ua', 'instant-mail.de', 'ip6.li', 'irish2me.com',
  'iwi.net', 'jetable.pp.ua', 'jnxjn.com', 'jourrapide.com',
  'kasmail.com', 'kaspop.com', 'killmail.com', 'killmail.net',
  'klassmaster.com', 'klzlk.com', 'koszmail.pl', 'kurzepost.de',
  'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'lol.ovpn.to', 'lolfreak.net', 'lookugly.com',
  'lortemail.dk', 'lr78.com', 'lroid.com', 'lukop.dk', 'm21.cc',
  'mail-filter.com', 'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net',
  'mail.zp.ua', 'mail1a.de', 'mail21.cc', 'mail2rss.org', 'mail333.com',
  'mailbidon.com', 'mailbiz.biz', 'mailblocks.com', 'mailbucket.org',
  'mailc.net', 'mailcat.biz', 'mailcatch.com', 'mailde.de', 'mailde.info',
  'maildrop.cf', 'maildrop.ga', 'maildrop.gq', 'maildrop.ml',
  'maileater.com', 'maileme101.com', 'mailezee.com', 'mailf5.com',
  'mailfall.com', 'mailfree.ga', 'mailfreeonline.com', 'mailguard.me',
  'mailin8r.com', 'mailinater.com', 'mailinator.net', 'mailinator.org',
  'mailinator.us', 'mailinator2.com', 'mailincubator.com',
  'mailismagic.com', 'mailjunk.cf', 'mailjunk.eu', 'mailjunk.ga',
  'mailjunk.gq', 'mailjunk.ml', 'mailme.ir', 'mailme.lv',
  'mailme24.com', 'mailmetrash.com', 'mailmoat.com', 'mailms.com',
  'mailnew.com', 'mailnowapp.com', 'mailnull.com', 'mailorg.org',
  'mailpick.biz', 'mailproxsy.com', 'mailquack.com', 'mailrock.biz',
  'mailscrap.com', 'mailseal.de', 'mailshell.com', 'mailsiphon.com',
  'mailslite.com', 'mailsourcecode.com', 'mailsucker.net', 'mailt.net',
  'mailtemporal.com', 'mailto.de', 'mailtome.de', 'mailtothis.com',
  'mailtrash.net', 'mailtrix.net', 'mailtv.net', 'mailwithyou.com',
  'mailworking.com', 'mailzi.com', 'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'manybrain.com', 'mbx.cc', 'mega.zik.dj',
  'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de', 'mezimages.net',
  'mfsa.ru', 'mierdamail.com', 'mintemail.com', 'misterpinball.de',
  'mjukglass.nu', 'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf',
  'mt2009.com', 'mt2014.com', 'mx0.wwwnew.eu', 'mycleaninbox.net',
  'mypartyclip.de', 'myphantomemail.com', 'mysamp.de', 'myspaceinc.com',
  'myspaceinc.net', 'myspaceinc.org', 'myspacepimpedup.com', 'myspamless.com',
  'mytempemail.com', 'mytempmail.com', 'mytrashmail.com', 'nabuma.com',
  'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net',
  'netmails.com', 'netmails.net', 'neverbox.com', 'nice-4u.com',
  'nincsmail.com', 'nnh.com', 'no-spam.ws', 'noblepioneer.com',
  'nomail.pw', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
  'nonspam.eu', 'nonspammer.de', 'noref.in', 'norseforce.com',
  'nospam.ze.tc', 'nospam4.us', 'nospamfor.us', 'nospamthanks.info',
  'notmailinator.com', 'nwldx.com', 'objectmail.com', 'obobbo.com',
  'odnorazovyj.ru', 'oneoffemail.com', 'oneoffmail.com', 'onewaymail.com',
  'onlatedotcom.info', 'online.ms', 'opayq.com', 'ordinaryamerican.net',
  'otherinbox.com', 'ovpn.to', 'owlpic.com', 'pancakemail.com',
  'pcusers.otherinbox.com', 'pjjkp.com', 'plexolan.de', 'poczta.onet.pl',
  'politikerclub.de', 'pooev.com', 'postalmail.biz', 'postfach2go.de',
  'powered.name', 'premium-mail.fr', 'prochina.biz', 'proxymail.eu',
  'prtnx.com', 'prtz.eu', 'punkass.com', 'putthisinyourspamdatabase.com',
  'pwrby.com', 'q.com', 'qisdo.com', 'qisoa.com', 'qoika.com',
  'quickinbox.com', 'quickmail.nl', 'rcpt.at', 're-gister.com',
  'reallymymail.com', 'realtyalerts.ca', 'recode.me', 'reconmail.com',
  'recursor.net', 'regbypass.com', 'regbypass.comsafe-mail.net',
  'rejo.technology', 'remarkable.rocks', 'rhyta.com', 'rklips.com',
  'rmqkr.net', 'royal.net', 'rppkn.com', 'rtrtr.com', 's0ny.net',
  'safe-mail.net', 'safersignup.de', 'safetymail.info', 'safetypost.de',
  'sandelf.de', 'saynotospams.com', 'schafmail.de', 'schrott-email.de',
  'secretemail.de', 'secure-mail.biz', 'senseless-entertainment.com',
  'services391.com', 'sharedmailbox.org', 'shieldemail.com', 'shiftmail.com',
  'shitmail.me', 'shitmail.org', 'shitware.nl', 'shmeriously.com',
  'shortmail.net', 'sibmail.com', 'sinnlos-mail.de', 'slapsfromlastnight.com',
  'slaskpost.se', 'slipry.net', 'slopsbox.com', 'slushmail.com',
  'smashmail.de', 'smellfear.com', 'smwg.info', 'snakemail.com',
  'sneakemail.com', 'sneakmail.de', 'snkmail.com', 'sofimail.com',
  'sofort-mail.de', 'sogetthis.com', 'solopiloopi.com', 'soodonims.com',
  'spam.la', 'spam.mn', 'spam.org.tr', 'spam.su', 'spam4.me',
  'spamavert.com', 'spambo.co', 'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamex.com', 'spamfree.eu',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgob.com', 'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'spamherelots.com', 'spamherelots.net',
  'spamhereplease.com', 'spamhereplease.net', 'spamhole.com',
  'spamify.com', 'spaminator.de', 'spamkill.info', 'spaml.com',
  'spaml.de', 'spammotel.com', 'spammy.host', 'spamoff.de',
  'spamslicer.com', 'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtrail.com', 'spamtrap.ro', 'speed.1s.fr',
  'spoofmail.de', 'squizzy.de', 'squizzy.eu', 'squizzy.net',
  'ssoia.com', 'startkeys.com', 'stinkefinger.net', 'stuffmail.de',
  'super-auswahl.de', 'supergreatmail.com', 'supermailer.jp',
  'superrito.com', 'superstachel.de', 'suremail.info', 'svk.jp',
  'sweetxxx.de', 'tafmail.com', 'tagyourself.com', 'talkinator.com',
  'tapchicuoihoi.com', 'teewars.org', 'teleworm.com', 'teleworm.us',
  'tempalias.com', 'tempe-mail.com', 'tempemail.biz', 'tempemail.com',
  'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail.eu',
  'tempmail.it', 'tempmail2.com', 'tempomail.fr', 'temporarily.de',
  'temporarioemail.com.br', 'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com',
  'tempsky.com', 'tempthe.net', 'tempymail.com', 'thankyou2010.com',
  'thc.st', 'thelimpidingtrough.com', 'themostemail.com', 'therealcommunity.org',
  'thisisnotmyrealemail.com', 'throam.com', 'throwam.com',
  'throwaway.email', 'throwaways.ml', 'throwjunk.com', 'tilien.com',
  'tittbit.in', 'tizi.com', 'tmailinator.com', 'toiea.com',
  'tonymanso.com', 'toomail.biz', 'topranklist.de', 'tradermail.info',
  'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash-mail.ga', 'trash-mail.io', 'trash-mail.net', 'trash2009.com',
  'trash2010.com', 'trash2011.com', 'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashimail.de', 'trashinbox.com', 'trashmail.at',
  'trashmail.com', 'trashmail.de', 'trashmail.eu', 'trashmail.io',
  'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.xyz',
  'trashmailer.com', 'trashymail.com', 'trashymail.net', 'trayna.com',
  'trbvm.com', 'trbvn.com', 'trbvo.com', 'trickmail.net', 'trillianpro.com',
  'tryalert.com', 'turual.com', 'twinmail.de', 'tyldd.com',
  'uggsrock.com', 'umail.net', 'uroid.com', 'us.af',
  'veryrealemail.com', 'vidchart.com', 'viditag.com', 'viewcastmedia.com',
  'viewcastmedia.net', 'viewcastmedia.org', 'viralplays.com',
  'vpn.st', 'vsimcard.com', 'vubby.com', 'wasteland.raubgraf.de',
  'webemail.me', 'weg-werf-email.de', 'wegwerf-email.at',
  'wegwerf-email.de', 'wegwerf-email.net', 'wegwerf-email.org',
  'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de',
  'wegwerfemail.info', 'wegwerfemail.net', 'wegwerfemail.org',
  'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org', 'wegwerfmailaddress.com', 'welikecookies.com',
  'wellhungover.com', 'willhackforfood.biz', 'willselfdestruct.com',
  'wilemail.com', 'wimsg.com', 'writeme.us', 'wronghead.com',
  'wuzupmail.net', 'www.e4ward.com', 'www.mailinator.com',
  'wwwnew.eu', 'xagloo.co', 'xagloo.com', 'xemaps.com',
  'xents.com', 'xmaily.com', 'xoxy.net', 'xsmail.com',
  'xww.ro', 'xyzfree.net', 'yapped.net', 'yeah.net',
  'yep.it', 'yogamaven.com', 'yopmail.fr', 'yopmail.net',
  'yourdomain.com', 'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'z1p.biz', 'za.com', 'zehnminuten.de', 'zehnminutenmail.de',
  'zetmail.com', 'zippymail.info', 'zoemail.com', 'zoemail.net',
  'zoemail.org', 'zomg.info', 'example.com', 'example.net',
  'example.org', 'test.com', 'test.net', 'test.org',
  'fake.com', 'fake.net', 'fake.org', 'noreply.com',
  'invalid.com', 'nowhere.com', 'nobody.com',
]);

// Legitimate domains always allowed
const allowedDomains = new Set([
  'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com',
  'icloud.com', 'protonmail.com', 'proton.me', 'me.com',
  'mac.com', 'live.com', 'msn.com', 'ymail.com',
  'aol.com', 'zoho.com', 'rediffmail.com', 'tutanota.com',
]);

const isDisposableEmail = (email) => {
  if (!email || typeof email !== 'string') return true;

  const lower = email.toLowerCase().trim();
  const atIndex = lower.lastIndexOf('@');
  if (atIndex === -1) return true;

  const domain = lower.slice(atIndex + 1);

  // Always allow known legitimate domains
  if (allowedDomains.has(domain)) return false;

  // Block known disposable domains
  if (disposableDomains.has(domain)) return true;

  // Block suspicious patterns
  const suspiciousPatterns = [
    /^temp/,        // tempemail, tempmail etc
    /temp$/,
    /^trash/,       // trashmail etc
    /^spam/,        // spammail etc
    /^fake/,        // fakemail etc
    /^disposable/,
    /^throwaway/,
    /^noreply/,
    /^no-reply/,
    /mailinator/,
    /yopmail/,
    /guerrilla/,
  ];

  if (suspiciousPatterns.some(p => p.test(domain))) return true;

  return false;
};

module.exports = isDisposableEmail;
